name: Build and Deploy Snapshot

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

permissions: {}

env:
  MAVEN_JDK_DEFAULT_VERSION: '25' # JDK version to run Maven with and use for compilation etc

jobs:
  build:
    strategy:
      matrix:
        jdk_test_version: [ '11', '17', '21', '25' ] # JDK version to run surefire/failsafe tests using
      fail-fast: false

    name: Build and Test (JDK ${{ matrix.jdk_test_version }})
    permissions:
      contents: read # to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    steps:
      - name: Install gpg secret key
        if: github.repository_owner == 'dependency-check'
        id: install-gpg-key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v6
      - name: Maven Integration Test Cache
        id: maven-it-cache
        uses: actions/cache@v5
        with:
          path: maven/target/local-repo
          key: mvn-it-repo
      - name: Check ODC Data Cache
        id: odc-data-cache
        uses: actions/cache@v5
        with:
          path: core/target/data
          key: odc-data
      - uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: '8.0.x'
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            ${{ matrix.jdk_test_version }}
            ${{ env.MAVEN_JDK_DEFAULT_VERSION }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
          server-id: central
          server-username: ${{ secrets.CENTRAL_USER }}
          server-password: ${{ secrets.CENTRAL_PASSWORD }}
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 6.0.2
      - name: Build/Test Snapshot with Maven
        id: build-snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USER }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: >
          mvn -V -s settings.xml 
          clean package verify source:jar javadoc:jar 
          ${{ steps.install-gpg-key.outcome == 'success' && '-Prelease gpg:sign deploy' || '' }} 
          -DreleaseTesting 
          -Dtoolchain.jdk.test.version=${{ matrix.jdk_test_version }} -Dtoolchain.jdk.test.home="$JAVA_HOME_${{ matrix.jdk_test_version }}_X64"
          --no-transfer-progress --batch-mode
      - name: SARIF Multitool
        uses: microsoft/sarif-actions@v0.2
        with:
          # Command to be sent to SARIF Multitool
          command: 'validate core/target/test-reports/Report.sarif'
      - name: Archive IT test logs
        id: archive-logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: it-test-logs-${{ matrix.jdk_test_version }}
          retention-days: 7
          path: maven/target/it/**/build.log
      - name: Archive code coverage results
        if: matrix.jdk_test_version == env.MAVEN_JDK_DEFAULT_VERSION
        id: archive-coverage
        uses: actions/upload-artifact@v6
        with:
          name: code-coverage-report
          retention-days: 7
          path: |
            **/target/jacoco-results/jacoco.xml
            **/target/jacoco-results/**/*.html
      - name: Archive Snapshot
        if: matrix.jdk_test_version == env.MAVEN_JDK_DEFAULT_VERSION
        id: archive-snapshot
        uses: actions/upload-artifact@v6
        with:
          name: archive-snapshot
          retention-days: 7
          path: |
            **/target/*.asc
            **/target/*.jar
            **/target/*.pom
            ant/target/*.zip
            cli/target/*.zip

  docker:
    permissions:
      contents: read # to fetch code (actions/checkout)

    name: Build and Test Docker
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.MAVEN_JDK_DEFAULT_VERSION }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
      - name: Download release build
        uses: actions/download-artifact@v7
        with:
          name: archive-snapshot
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: ./build-docker.sh
      - name: build scan target
        run: mvn -V -s settings.xml package -DskipTests=true --no-transfer-progress --batch-mode
      - name: Test Docker Image
        run: ./test-docker.sh
